apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datetime
spec:
  replicas: 2
  template:
    metadata:
      name: datetime
      labels:
        app: datetime
        env: test
    spec:
      containers:
        - image: eu.gcr.io/astute-buttress-256817/datetime-service:latest
          imagePullPolicy: Always
          name: datetime
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: datetime
#  annotations:
#    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: datetime
