apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weekday
spec:
  replicas: 2
  template:
    metadata:
      name: weekday
      labels:
        app: weekday
        env: test
    spec:
      containers:
        - image: eu.gcr.io/astute-buttress-256817/weekday-service:latest
          imagePullPolicy: Always
          name: weekday
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weekday
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: weekday
